DROP TABLE IF EXISTS T_CUSTOMER;
DROP TABLE IF EXISTS T_ADDRESS;

CREATE TABLE T_ADDRESS(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ADDR_LINE1 VARCHAR(50) NOT NULL,
  ADDR_LINE2 VARCHAR(50) DEFAULT NULL,
  STATE VARCHAR(20) DEFAULT NOT NULL,
  ZIP_CD VARCHAR(10) DEFAULT NOT NULL,
  COUNTRY VARCHAR(15) DEFAULT NOT NULL
);

CREATE TABLE T_CUSTOMER(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID NUMBER NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) DEFAULT NULL,
  DOB DATE DEFAULT NULL,
  VERSION NUMBER DEFAULT NOT NULL,
  ADDRESS_ID INT NOT NULL REFERENCES T_ADDRESS(ID),
  FOREIGN KEY (ADDRESS_ID) REFERENCES T_ADDRESS(ID)
);